import { backpack, deliveryTruck, headphones, jeans, returnPolicy, shoes, smartPhone, smartWatch, warranty, } from "../../../utils/imageConstants";


export const deals = [{
    id: 1,
    name: "Premium Wireless Headphones",
    rating: "4.3",
    ratingCount: "235",
    discountedPrice: "4999",
    originalPrice: "8999",
    discount: "50",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: headphones,
    allProductImagesUrl: [headphones, smartPhone, jeans],
    deliveryDetails: [{ imageUrl: deliveryTruck, deliveryData: "Free Delivery", timePeriod: "Delivery by Tomorrow" },
    { imageUrl: returnPolicy, deliveryData: "7 Days Return Policy", timePeriod: "Easy returns and refunds" },
    { imageUrl: warranty, deliveryData: "Warranty", timePeriod: "1 Year" }],
    specifications: {
        brand: "AudioTech",
        batteryLife: "30 hours",
        connectivity: "Bluetooth 5.0",
        weight: "250g",
    },
    details: "Very best product in the market",
    reviews: [
        // { name: "Govind", review: "nice product", rating: "3.5" },
        // { name: "Ram", review: "good product", rating: "4.5" },
        // { name: "Venkat", review: "bad product", rating: "4.0" },
        // { name: "Siva", review: "not bad product", rating: "2.5" },
    ]
},
{
    id: 2,
    name: "Smart Fitness Watch",
    rating: "4.2",
    ratingCount: "4534",
    discountedPrice: "3999",
    originalPrice: "7999",
    discount: "40",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: smartWatch,
    allProductImagesUrl: [smartWatch, headphones, jeans],
    deliveryDetails: [{ imageUrl: deliveryTruck, deliveryData: "Free Delivery", timePeriod: "Delivery by Tomorrow" },
    { imageUrl: returnPolicy, deliveryData: "7 Days Return Policy", timePeriod: "Easy returns and refunds" },
    { imageUrl: warranty, deliveryData: "Warranty", timePeriod: "1 Year" }],
    specifications: {
        brand: "AudioTech",
        batteryLife: "30 hours",
        connectivity: "Bluetooth 5.0",
        weight: "250g",
    },
    details: "Very best product in the market",
    reviews: [
        { name: "Govind", review: "nice product", rating: "3.5" },
        { name: "Ram", review: "good product", rating: "4.5" },
        { name: "Venkat", review: "bad product", rating: "4.0" },
        { name: "Siva", review: "not bad product", rating: "2.5" },
    ]
},
{
    id: 3,
    name: "Casual Denim Jeans",
    rating: "3.5",
    ratingCount: "65",
    discountedPrice: "1500",
    originalPrice: "2900",
    discount: "70",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: jeans,
    allProductImagesUrl: [jeans, smartPhone, headphones],
    deliveryDetails: [{ imageUrl: deliveryTruck, deliveryData: "Free Delivery", timePeriod: "Delivery by Tomorrow" },
    { imageUrl: returnPolicy, deliveryData: "7 Days Return Policy", timePeriod: "Easy returns and refunds" },
    { imageUrl: warranty, deliveryData: "Warranty", timePeriod: "1 Year" }],
    specifications: {
        brand: "AudioTech",
        batteryLife: "30 hours",
        connectivity: "Bluetooth 5.0",
        weight: "250g",
    },
    details: "Very best product in the market",
    reviews: [
        { name: "Govind", review: "nice product", rating: "3.5" },
        { name: "Ram", review: "good product", rating: "4.5" },
        { name: "Venkat", review: "bad product", rating: "4.0" },
        { name: "Siva", review: "not bad product", rating: "2.5" },
    ]
},
{
    id: 4,
    name: "Running Shoes",
    rating: "5.0",
    ratingCount: "6868",
    discountedPrice: "3000",
    originalPrice: "5000",
    discount: "40",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: shoes,
    allProductImagesUrl: [shoes, smartPhone, headphones],
    deliveryDetails: [{ imageUrl: deliveryTruck, deliveryData: "Free Delivery", timePeriod: "Delivery by Tomorrow" },
    { imageUrl: returnPolicy, deliveryData: "7 Days Return Policy", timePeriod: "Easy returns and refunds" },
    { imageUrl: warranty, deliveryData: "Warranty", timePeriod: "1 Year" }],
    specifications: {
        brand: "AudioTech",
        batteryLife: "30 hours",
        connectivity: "Bluetooth 5.0",
        weight: "250g",
    },
    details: "Very best product in the market",
    reviews: [
        { name: "Govind", review: "nice product", rating: "3.5" },
        { name: "Ram", review: "good product", rating: "4.5" },
        { name: "Venkat", review: "bad product", rating: "4.0" },
        { name: "Siva", review: "not bad product", rating: "2.5" },
    ]
},
{
    id: 5,
    name: "Latest Smartphone",
    rating: "4.2",
    ratingCount: "2",
    discountedPrice: "65000",
    originalPrice: "79000",
    discount: "10",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: smartPhone,
    allProductImagesUrl: [smartPhone, shoes, headphones],
    deliveryDetails: [{ imageUrl: deliveryTruck, deliveryData: "Free Delivery", timePeriod: "Delivery by Tomorrow" },
    { imageUrl: returnPolicy, deliveryData: "7 Days Return Policy", timePeriod: "Easy returns and refunds" },
    { imageUrl: warranty, deliveryData: "Warranty", timePeriod: "1 Year" }],
    specifications: {
        brand: "AudioTech",
        batteryLife: "30 hours",
        connectivity: "Bluetooth 5.0",
        weight: "250g",
    },
    details: "Very best product in the market",
    reviews: [
        { name: "Govind", review: "nice product", rating: "3.5" },
        { name: "Ram", review: "good product", rating: "4.5" },
        { name: "Venkat", review: "bad product", rating: "4.0" },
        { name: "Siva", review: "not bad product", rating: "2.5" },
    ]
},
{
    id: 6,
    name: "Premium  Backpack",
    rating: "3.0",
    ratingCount: "223",
    discountedPrice: "1999",
    originalPrice: "4999",
    discount: "40",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: backpack,
    allProductImagesUrl: [backpack, smartPhone, headphones],
    deliveryDetails: [{ imageUrl: deliveryTruck, deliveryData: "Free Delivery", timePeriod: "Delivery by Tomorrow" },
    { imageUrl: returnPolicy, deliveryData: "7 Days Return Policy", timePeriod: "Easy returns and refunds" },
    { imageUrl: warranty, deliveryData: "Warranty", timePeriod: "1 Year" }],
    specifications: {
        brand: "AudioTech",
        batteryLife: "30 hours",
        connectivity: "Bluetooth 5.0",
        weight: "250g",
    },
    details: "Very best product in the market",
    reviews: [
        { name: "Govind", review: "nice product", rating: "3.5" },
        { name: "Ram", review: "good product", rating: "4.5" },
        { name: "Venkat", review: "bad product", rating: "4.0" },
        { name: "Siva", review: "not bad product", rating: "2.5" },
    ]
},
]