import { backpack, headphones, jeans, shoes, smartPhone, smartWatch, } from "../../../utils/imageConstants";


export const deals = [{
    name: "Premium Wireless Headphones",
    rating: "4.3",
    ratingCount: "235",
    discountedPrice: "4999",
    originalPrice: "8999",
    discount: "50",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: headphones,
},
{
    name: "Smart Fitness Watch",
    rating: "4.2",
    ratingCount: "4534",
    discountedPrice: "3999",
    originalPrice: "7999",
    discount: "40",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: smartWatch,
},
{
    name: "Casual Denim Jeans",
    rating: "3.5",
    ratingCount: "65",
    discountedPrice: "1500",
    originalPrice: "2900",
    discount: "70",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: jeans,
},
{
    name: "Running Shoes",
    rating: "5.0",
    ratingCount: "6868",
    discountedPrice: "3000",
    originalPrice: "5000",
    discount: "40",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: shoes,
},
{
    name: "Latest Smartphone",
    rating: "4.2",
    ratingCount: "2",
    discountedPrice: "65000",
    originalPrice: "79000",
    discount: "10",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: smartPhone,
},
{
    name: "Premium  Backpack",
    rating: "3.0",
    ratingCount: "223",
    discountedPrice: "1999",
    originalPrice: "4999",
    discount: "40",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: backpack,
},
{
    name: "Premium Wireless Headphones",
    rating: "4.3",
    ratingCount: "235",
    discountedPrice: "4999",
    originalPrice: "8999",
    discount: "50",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: headphones,
},
{
    name: "Smart Fitness Watch",
    rating: "4.2",
    ratingCount: "4534",
    discountedPrice: "3999",
    originalPrice: "7999",
    discount: "40",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: smartWatch,
},
{
    name: "Casual Denim Jeans",
    rating: "3.5",
    ratingCount: "65",
    discountedPrice: "1500",
    originalPrice: "2900",
    discount: "70",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: jeans,
},
{
    name: "Running Shoes",
    rating: "5.0",
    ratingCount: "6868",
    discountedPrice: "3000",
    originalPrice: "5000",
    discount: "40",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: shoes,
},
{
    name: "Latest Smartphone",
    rating: "4.2",
    ratingCount: "2",
    discountedPrice: "65000",
    originalPrice: "79000",
    discount: "10",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: smartPhone,
},
{
    name: "Premium  Backpack",
    rating: "3.0",
    ratingCount: "223",
    discountedPrice: "1999",
    originalPrice: "4999",
    discount: "40",
    isWishlisted: false,
    isAddedToCart: false,
    imageUrl: backpack,
}]